
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
     
     
      >
           <header className="bg-sky-300 w-full ">This is header</header>
        {children}
      </body>
    </html>
  );
}
